# Generated by Django 5.0.1 on 2024-05-26 20:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0004_division'),
    ]

    operations = [
        migrations.CreateModel(
            name='DeviceType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('C_Name', models.CharField(help_text='Введите тип прибора', max_length=200, verbose_name='Наименование')),
                ('C_Manufacturer', models.CharField(blank=True, help_text='Введите производителя', max_length=200, null=True, verbose_name='Производитель')),
            ],
        ),
        migrations.AlterField(
            model_name='division',
            name='C_Name',
            field=models.CharField(max_length=100, verbose_name='Наименование'),
        ),
        migrations.AlterField(
            model_name='division',
            name='D_Date_Begin',
            field=models.DateField(blank=True, null=True, verbose_name='Дата открытия'),
        ),
        migrations.AlterField(
            model_name='division',
            name='D_Date_End',
            field=models.DateField(blank=True, null=True, verbose_name='Дата закрытия'),
        ),
        migrations.CreateModel(
            name='Device',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('C_Serial_Number', models.CharField(max_length=200, verbose_name='Серийный номер')),
                ('D_Replace_Date', models.DateField(blank=True, null=True, verbose_name='Дата снятия')),
                ('F_Division', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='catalog.division', verbose_name='Цех')),
                ('F_Device_Types', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='catalog.devicetype', verbose_name='Тип прибора')),
            ],
            options={
                'ordering': ['D_Replace_Date'],
            },
        ),
    ]
