# Generated by Django 5.0.1 on 2024-05-30 20:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0005_devicetype_alter_division_c_name_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='DeliveryMethod',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('C_Name', models.CharField(help_text='Введите тип прибора', max_length=200, verbose_name='Наименование')),
            ],
        ),
        migrations.CreateModel(
            name='TariffZone',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('C_Name', models.CharField(help_text='Введите тип прибора', max_length=200, verbose_name='Наименование')),
            ],
        ),
        migrations.CreateModel(
            name='MeterMeasure',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('N_Digits', models.FloatField(verbose_name='Разрядность')),
                ('F_Devices', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catalog.device', verbose_name='Прибор')),
                ('F_Tariff_Zones', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catalog.tariffzone', verbose_name='Тарифная зона')),
            ],
        ),
    ]
