# Generated by Django 5.0.1 on 2024-05-30 21:17

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0007_alter_deliverymethod_c_name_alter_tariffzone_c_name_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='meterreadings',
            name='C_Notes',
            field=models.CharField(max_length=200, null=True, verbose_name='Примечание'),
        ),
        migrations.AlterField(
            model_name='meterreadings',
            name='F_Creator',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Автор записи'),
        ),
    ]
