# Generated by Django 5.0.1 on 2024-05-31 09:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0008_alter_meterreadings_c_notes_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='meterreadings',
            name='Img',
            field=models.ImageField(blank=True, null=True, upload_to='img/', verbose_name='Вложение'),
        ),
    ]
