# Generated by Django 5.0.1 on 2024-06-05 19:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0011_alter_meterreading_options_division_c_notes'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='device',
            options={'ordering': ['C_Serial_Number', 'D_Replace_Date']},
        ),
        migrations.AlterField(
            model_name='meterreading',
            name='C_Notes',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Примечание'),
        ),
        migrations.AlterField(
            model_name='meterreading',
            name='Img',
            field=models.ImageField(blank=True, null=True, upload_to='img/', verbose_name='Фото'),
        ),
    ]
